spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/porlat #ссылка на realm
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/porlat #ссылка на realm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: springsecurity
            client-secret: CvWGEyBEeRv7VR1pWUccNzb5xYBwy5uq
            scope: openid
server:
  port: 8081
logging:
  level:
    org.springframework.security: TRACE